import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c3c6d7",
        "on-background": "#131b2e",
        "on-primary-fixed": "#00174b",
        "primary-fixed-dim": "#b4c5ff",
        tertiary: "#824500",
        "surface-container-highest": "#dae2fd",
        "inverse-surface": "#283044",
        "surface-bright": "#faf8ff",
        "tertiary-fixed-dim": "#ffb77d",
        "on-tertiary-fixed-variant": "#6e3900",
        "surface-container-high": "#e2e7ff",
        "secondary-fixed-dim": "#68dba9",
        "primary-container": "#2563eb",
        "tertiary-container": "#a65900",
        "on-tertiary-container": "#ffede1",
        "on-tertiary-fixed": "#2f1500",
        "surface-container": "#eaedff",
        "secondary-fixed": "#85f8c4",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#003ea8",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#00714e",
        "surface-tint": "#0053db",
        "on-secondary-fixed-variant": "#005137",
        "tertiary-fixed": "#ffdcc3",
        "on-error-container": "#93000a",
        "on-primary-container": "#eeefff",
        "on-surface": "#131b2e",
        background: "#faf8ff",
        "inverse-primary": "#b4c5ff",
        "on-surface-variant": "#434655",
        "error-container": "#ffdad6",
        "surface-variant": "#dae2fd",
        error: "#ba1a1a",
        primary: "#004ac6",
        "on-secondary": "#ffffff",
        "secondary-container": "#82f5c1",
        "inverse-on-surface": "#eef0ff",
        "surface-dim": "#d2d9f4",
        "primary-fixed": "#dbe1ff",
        "surface-container-low": "#f2f3ff",
        outline: "#737686",
        surface: "#faf8ff",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#002114",
        "on-primary": "#ffffff",
        secondary: "#006c4a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        gutter: "1.5rem",
        margin: "2rem",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
        headline: ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "headline-xl": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "headline-lg": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "headline-md": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "headline-sm": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "body-sm": ["var(--font-inter)", "sans-serif"],
        "label-lg": ["var(--font-inter)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
        "code-sm": ["ui-monospace", "monospace"],
      },
      fontSize: {
        "headline-xl": ["36px", { lineHeight: "44px", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
        "code-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
